[workspace]
members = ["junction-core", "junction-python", "xtask"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/junction-labs/junction-client"

[workspace.dependencies]

arc-swap = "1.7"
bytes = "1.6"
crossbeam-skiplist = "0.1"
enum-map = "2.7"
futures = "0.3"
h2 = "0.3"
http = "1.1"
tokio = { version = "1.38", default-features = false }
tokio-stream = "0.1"
tonic = "0.11"
tonic-reflection = "0.11"
once_cell = "1.19"
petgraph = "0.6"
prost = "0.12"
rand = "0.8"
serde = { version = "1.0", default-features = false }
serde_json = "1.0"
serde_yml = "0.0.10"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
xds-api = { git = "ssh://git@github.com/junction-labs/xds-api.git", default-features = false }

junction-core = { version = "0.1.0", path = "junction-core" }
