FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /app
RUN apt update
RUN apt install -y python3 python3-pip python3.11-venv python-is-python3
RUN apt install -y 

FROM chef AS planner
COPY ./junction-python ./junction-python
COPY ./xtask ./xtask
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./crates ./crates
COPY ./.cargo ./.cargo
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY ./junction-python ./junction-python
COPY ./xtask ./xtask
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./crates ./crates
COPY ./.cargo ./.cargo
RUN cargo xtask python-build --maturin build

FROM debian:bookworm-slim AS runtime
RUN apt-get update
RUN apt-get install -y python3 python3-pip python-is-python3
WORKDIR /app
COPY --from=builder /app/target/wheels/junction-*.whl .
RUN pip install ./*.whl --break-system-packages
ADD junction-python/samples/routing-and-load-balancing/client.py .
CMD ["python", "./client.py"]
