FROM python:3.12

# the name of the junction package to install with pip this can be either a pypi
# package name, a wheel URL, or a local path to a wheel.
#
# NOTE: If you're using this as a local path to a wheel, you may have to mount
# the wheel into the container with Docker's --volume arg.
ARG junction_wheel

WORKDIR /client

ADD ${junction_wheel} .

RUN python -m venv .venv
RUN .venv/bin/pip install --upgrade pip
RUN .venv/bin/pip install pyyaml
RUN .venv/bin/pip install *.whl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin
ADD junction-python/samples/routing-and-load-balancing/client.py .
ENTRYPOINT [".venv/bin/python", "./client.py"]
