---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jct-simple-app
  labels:
    app: jct-simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jct-simple-app
  template:
    metadata:
      labels:
        app: jct-simple-app
    spec:
      containers:
        - name: jct-simple-app
          image: jct_simple_app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/server.py"]
          env:
            - name: TARGET
              value: "jct-simple-app"
---
apiVersion: v1
kind: Service
metadata:
  name: jct-simple-app
spec:
  type: ClusterIP
  selector:
    app: jct-simple-app
  ports:
    - port: 8008
      targetPort: 8008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jct-simple-app-v2
  labels:
    app: jct-simple-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jct-simple-app-v2
  template:
    metadata:
      labels:
        app: jct-simple-app-v2
    spec:
      containers:
        - name: jct-simple-app-v2
          image: jct_simple_app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/server.py"]
          env:
            - name: TARGET
              value: "jct-simple-app-v2"
---
apiVersion: v1
kind: Service
metadata:
  name: jct-simple-app-v2
spec:
  type: ClusterIP
  selector:
    app: jct-simple-app-v2
  ports:
    - port: 8008
      targetPort: 8008
