# https://www.mkdocs.org/user-guide/configuration/

site_name: Junction User Guide
site_url: https://docs.junctionlabs.io/
repo_url: https://github.com/junction-labs/junction-client
repo_name: junction-labs/junction-client
docs_dir: source
strict: true
nav:
  - "Overview":
      - index.md
      - overview/core-concepts.md
  - "Getting Started":
      - getting-started/index.md
      - getting-started/ezbake.md
      - getting-started/node.md
      - getting-started/python.md
      - getting-started/rust.md
      - getting-started/configuring-junction.md
  - "Reference":
      - "reference/api.md"
not_in_nav: |
  /_build/
validation:
  links:
    absolute_links: ignore

theme:
  name: material
  locale: en
  custom_dir: source/_build/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: _build/assets/logo.png
  features:
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: [".", "source/src/"]
      check_paths: true
      dedent_subsections: true

plugins:
  - search:
      lang: en
  - markdown-exec
  - macros:
      module_name: source/_build/scripts/macro
