name: Build Rust documentation

on:
  pull_request:
    paths:
      - crates/**
      - .github/workflows/docs-rust.yml
  push:
    branches:
      - main
    paths:
      - crates/**
      - .github/workflows/docs-rust.yml
  repository_dispatch:
    types:
      - rust-release
env:
  rust_stable: stable

concurrency:
  group: ${{ github.job }}-${{ github.ref }} 

permissions:
  contents: write

jobs:
  build-rust-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust @ ${{ env.rust_stable }}"
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2

      - name: Build Rust documentation
        env:
          RUSTDOCFLAGS: --cfg docsrs --allow=rustdoc::redundant-explicit-links
        run: cargo doc --no-deps -p junction-api -p junction-core

      - name: Deploy Rust docs
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
          target-folder: api/rust/dev
          single-commit: true

      # Make sure documentation artifacts are not cached
      - name: Clean up documentation artifacts
        if: ${{ github.ref_name == 'main' }}
        run: rm -rf target/doc
