name: Build Node reference documentation

on:
  pull_request:
    paths:
      - junction-node/**
      - .github/workflows/docs-node.yml
  push:
    branches:
      - main
    paths:
      - junction-node/**
      - .github/workflows/docs-node.yml
  repository_dispatch:
    types:
      - node-release

env:
  rust_stable: stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-python-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: "Install Rust @ ${{ env.rust_stable }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build and install junction node
        run: cargo xtask node-build

      - name: Build documentation
        run: cargo xtask node-docs

      - name: Deploy docs for latest development version
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junction-node/docs
          target-folder: api/node/dev
          single-commit: true

      - name: Deploy docs for latest release version - stable
        if: github.event_name == 'repository_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junction-node/docs
          target-folder: api/node/stable
          single-commit: true
