name: Build Python documentation

on:
  pull_request:
    paths:
      - junction-python/**
      - .github/workflows/docs-python.yml
  push:
    branches:
      - main
    paths:
      - junction-python/**
      - .github/workflows/docs-python.yml
  repository_dispatch:
    types:
      - python-release

env:
  rust_stable: stable

concurrency:
  group: ${{ github.job }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  build-python-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: "Install Rust @ ${{ env.rust_stable }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create virtual environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

      - name: Install dependencies
        run: uv pip install -r junction-python/requirements-dev.txt -r junction-python/docs/requirements.txt

      - name: Build and install junction python
        run: cargo xtask python-build

      - name: Build documentation
        env:
          JUNCTION_VERSION: ${{ github.event.client_payload.version || 'main' }}
        run: cargo xtask python-docs

      - name: Deploy docs for latest development version
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junction-python/docs/build/html
          target-folder: api/python/dev
          single-commit: true

      - name: Deploy docs for latest release version - versioned
        if: github.event_name == 'repository_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junction-python/docs/build/html
          target-folder: api/python/version/${{ github.event.client_payload.maj_min_version }}
          single-commit: true

      - name: Deploy docs for latest release version - stable
        if: github.event_name == 'repository_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: junction-python/docs/build/html
          target-folder: api/python/stable
          single-commit: true
