name: junction-python CI

on:
  push:
    branches: ["main"]
    paths:
      - "junction-python/**"
      - ".github/workflows/junction-python-ci.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "junction-python/**"
      - ".github/workflows/junction-python-ci.yml"

env:
  CARGO_TERM_COLOR: always
  rust_stable: stable
  rust_min: 1.81
  python_stable: 3.12
  python_min: 3.9

jobs:
  # Python CI steps
  #
  # these lean on xtask tasks so they're similar to what you'd run locally
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - python: 3.12
            rust: stable
          - python: 3.12
            rust: 1.81
          - python: 3.9
            rust: stable
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust @ ${{ matrix.version.rust }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version.rust }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: "Set up Python @ ${{ matrix.version.python }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version.python }}

      - name: build python
        run: cargo xtask python build

      - name: check for uncommitted changes
        run: cargo xtask check-diffs

      - name: lint
        run: cargo xtask python lint

      - name: run tests
        run: cargo xtask python test
