# CI for all of the core Junction client crates.
#
# CI actually covering everything in core depends on having all of the crates
# in crates/* listed as default-members of the workspace in Cargo.toml.

name: junction-core CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "crates/**"
      - ".github/workflows/junction-ci.yml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "crates/**"
      - ".github/workflows/junction-ci.yml"

env:
  CARGO_TERM_COLOR: always
  rust_stable: stable
  rust_min: 1.79

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust @${{ env.rust_min }}"
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.rust_min }}
    - uses: Swatinem/rust-cache@v2
    - name: check
      run: cargo check
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust @${{ env.rust_stable }}"
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.rust_stable }}
    - uses: Swatinem/rust-cache@v2
    - name: test
      run: cargo test
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust @ ${{ env.rust_stable }}"
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.rust_stable }}
    - uses: Swatinem/rust-cache@v2
    - name: clippy
      run: cargo clippy --tests --all-features --no-deps -- -D warnings -D clippy::dbg_macro
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust @ ${{ env.rust_stable }}"
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.rust_stable }}
    - uses: Swatinem/rust-cache@v2
    - name: fmt
      run: |
        if ! rustfmt --check --edition 2021 $(git ls-files 'crates/*.rs'); then
          echo "rustfmt found un-formatted files" >&2
          exit 1
        fi
