name: junction-node CI

on:
  push:
    branches: ["main"]
    paths:
      - "junction-node/**"
      - ".github/workflows/junction-node-ci.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "junction-node/**"
      - ".github/workflows/junction-node-ci.yml"

env:
  CARGO_TERM_COLOR: always
  rust_stable: stable
  rust_min: 1.81
  node_lts: 20.x

jobs:
  # Rust CI steps
  #
  # These should be largely the same as the steps in junction-core-ci.yml but
  # testing a different package.
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust @${{ env.rust_min }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_min }}

      - uses: Swatinem/rust-cache@v2

      - name: check
        run: cargo xtask node build

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust @ ${{ env.rust_stable }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_lts }}
          cache: npm
          cache-dependency-path: junction-node/package-lock.json

      - name: build
        run: cargo xtask node build --clean-install

      - name: lint
        run: cargo xtask node lint

      - name: check for uncommitted changes
        run: cargo xtask check-diffs

      # TODO: add some node tests
      # - name: run node tests
      #   run: cargo xtask node test
