name: Regression Build and Test

on: 
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo xtask python-build
      
    - name: Run tests
      run: cargo xtask python-test
